In [1]:
import torch
import numpy as np

In [3]:
data = [[1,2],[3,4]]
print(type(data))
tensor_data = torch.tensor(data)
print(type(tensor_data))

<class 'list'>
<class 'torch.Tensor'>


In [4]:
numpy_data = np.array(data)
print(type(numpy_data))
tensor_data = torch.from_numpy(numpy_data)
print(type(tensor_data))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [5]:
x_ones = torch.ones_like(tensor_data)
x_ones

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [7]:
x_rand_float = torch.rand_like(tensor_data, dtype = torch.float)
x_rand_float

tensor([[0.7349, 0.3080],
        [0.4027, 0.6830]])

In [10]:
# x_rand_int = torch.rand_like(tensor_data, dtype = torch.int)
# x_rand_int

In [11]:
shape = (2,3)
random = torch.rand(shape)
ones = torch.ones(shape)
zeros = torch.zeros(shape)

In [12]:
random

tensor([[0.0145, 0.0774, 0.0512],
        [0.4908, 0.9911, 0.9198]])

In [13]:
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [14]:
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [15]:
print(random.shape)
print(random.dtype)
print(random.device)

torch.Size([2, 3])
torch.float32
cpu


In [16]:
fourones = torch.ones(4,4)
fourones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
fourones[0]

tensor([1., 1., 1., 1.])

In [23]:
fourones[:,1]

tensor([1., 1., 1., 1.])